sudo: required
language: generic
services:
  - docker

# before_install:
#   - docker build -t saurabhkumardocker/react-test -f ./client/Dockerfile.dev ./client

# script:
#   - docker run saurabhkumardocker/react-test npm test -- --coverage

after_success:
  - docker build -t saurabhkumardocker/multi-client ./client
  - docker build -t saurabhkumardocker/multi-nginx ./nginx
  - docker build -t saurabhkumardocker/multi-server ./server
  - docker build -t saurabhkumardocker/multi-worked ./worker
  #Login to docker cli
  # echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin 
  - docker login -u "$DOCKER_ID" -p "$DOCKER_PASSWORD"
  #take those images and push them to docker-hub.
  - docker push saurabhkumardocker/multi-client
  - docker push saurabhkumardocker/multi-nginx
  - docker push saurabhkumardocker/multi-server
  - docker push saurabhkumardocker/multi-worker

deploy:
  provider: elasticbeanstalk
  region: eu-west-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-eu-west-1-757069236268
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"




